[package]
name = "skyspell_core_tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
skyspell_core = { path = "../core" }
skyspell_tests = { path = "../tests" }
tempfile = "3.2.0"
