[package]
name = "rcspell"
version = "0.1.0"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
diesel = { version = "1.4.6", features = ["sqlite"] }
diesel_migrations = "1.4.0"
