[package]
name = "kak_spell"
version = "0.2.1"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
edition = "2018"
readme = "README.md"
description = "Enchant wrapper for Kakoune"
repository = "https://git.sr.ht/~dmerej/kak-spell"
license = "BSD-3-Clause"
keywords = ["spell", "cli", "kakoune"]

[dependencies]
anyhow = "1.0.40"
clap = "3.0.0-beta.2"
colored = "2.0.0"
dialoguer = "0.8.0"
diesel = { version = "1.4.6", features = ["sqlite"] }
diesel_migrations = "1.4.0"
dirs-next = "2.0.0"
enchant = "0.2.0"
itertools = "0.10.0"
lazy_static = "1.4.0"
platform-dirs = "0.3.0"
regex = "1.5.4"

[[bin]]
name = "kak-spell"
path = "src/main.rs"

[dev-dependencies]
paste = "1.0.5"
