[package]
name = "rcspell"
version = "0.1.0"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = "1.4.6"
