#!/bin/bash

set -e

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
  if [[ "${local_sha}" = $z40 ]]; then
    echo "Deleting stuff, nothing to do"
  else
    cargo clippy -- -A clippy::extra_unused_lifetimes -D clippy::unwrap_used
    cargo clippy --all-targets -- -A clippy::extra_unused_lifetimes --deny warnings
    cargo test
    cargo run --bin skyspell -- check --non-interactive
    cargo install --locked --path crates/cli/
    cargo install --locked --path crates/kak/
  fi
done

exit 0
