[package]
name = "skyspell_aspell"
version = "0.1.0"
edition = "2021"
description = "Implementation of the skyspell Checker trait using aspell directly"
publish = false

[dependencies]
anyhow = "1.0.40"
skyspell_core = { path = "../core" }
