global = [
    "Backend",
    "Baz",
    "CHANGELOG",
    "CONFIG",
    "Cli",
    "Config",
    "Dimitri",
    "Dirs",
    "HEXA",
    "Http",
    "IDENT",
    "Init",
    "Linters",
    "MERCHANTABILITY",
    "Merejkowsky",
    "Ok",
    "README",
    "Redistributions",
    "Sqlite",
    "Substring",
    "TODO",
    "Tmux",
    "UTF",
    "Whitespace",
    "XDG",
    "ada",
    "api",
    "args",
    "backend",
    "backends",
    "baz",
    "cd",
    "changelog",
    "chrono",
    "ci",
    "cli",
    "cmd",
    "config",
    "cpp",
    "darwin",
    "dev",
    "dir",
    "dirs",
    "enum",
    "env",
    "environ",
    "favicon",
    "filesystem",
    "fs",
    "github",
    "gitignore",
    "goto",
    "homebrew",
    "ico",
    "init",
    "io",
    "js",
    "json",
    "latin",
    "lineno",
    "linux",
    "lossy",
    "md",
    "msvc",
    "param",
    "pc",
    "pre",
    "py",
    "readme",
    "repo",
    "ripgrep",
    "semver",
    "sha",
    "src",
    "stdin",
    "stdout",
    "substring",
    "svg",
    "tempdir",
    "textwrap",
    "tmp",
    "tmux",
    "toml",
    "travis",
    "tty",
    "txt",
    "unicode",
    "unix",
    "url",
    "urls",
    "utf",
    "uuid",
    "vec",
    "whitespace",
]

[extensions]
kak = [
    "Buf",
    "Gl",
    "fi",
    "gi",
    "params",
    "printf",
    "pwd",
    "str",
]
py = [
    "Popen",
    "args",
    "breakpoint",
    "env",
    "fetchall",
    "fmt",
    "len",
    "os",
    "pathlib",
    "py",
    "pytest",
    "splitlines",
    "sqlite",
    "startswith",
    "stdout",
    "str",
    "subprocess",
    "textwrap",
    "tomllib",
]
rs = [
    "Bool",
    "Buf",
    "Deque",
    "Deserialize",
    "Eq",
    "Fn",
    "Formatter",
    "Itertools",
    "Mut",
    "Str",
    "Vec",
    "arg",
    "bool",
    "buf",
    "canonicalize",
    "cfg",
    "cmp",
    "const",
    "dbg",
    "de",
    "dedent",
    "deserialize",
    "dyn",
    "enum",
    "eprintln",
    "eq",
    "extern",
    "ffi",
    "fmt",
    "fn",
    "impl",
    "io",
    "iter",
    "len",
    "lt",
    "mut",
    "num",
    "ok",
    "os",
    "pathdiff",
    "pos",
    "println",
    "rsplit",
    "ser",
    "stdin",
    "stdout",
    "str",
    "struct",
    "tt",
    "ty",
    "usize",
]
sql = ["BIGINT"]
toml = ["pathdiff"]
