[package]
name = "skyspell_core"
description = "skyspell core library"
version = "0.0.0"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://git.sr.ht/~dmerej/skyspell"
publish = false

[dependencies]
anyhow = "1.0.40"
dialoguer = "0.8.0"
lazy_static = "1.4.0"
pathdiff = "0.2.0"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.5", features = ["std"] }
