[package]
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
name = "skyspell_core"
description = "skyspell core library"
version = "0.3.1"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://git.sr.ht/~dmerej/skyspell"
publish = true

[dependencies]
anyhow = "1.0.40"
diesel_migrations = "1.4.0"
diesel = { version = "1.4.8", features = ["sqlite"] }
directories-next = "2.0.0"
enchant = "0.3.0"
ignore = "0.4.18"
kdl = "4.3.0"
lazy_static = "1.4.0"
pathdiff = "0.2.0"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.2.0"
time = { version = "0.3.5", features = ["std"] }

[dev-dependencies]
textwrap = "0.15.0"
