[package]
name = "skyspell_core"
version = "0.6.1"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
edition = "2021"
readme = "README.md"
description = "Command line spell checker with Kakoune integration"
repository = "https://git.sr.ht/~dmerej/skyspell"
license = "BSD-3-Clause"
keywords = ["spell", "cli", "kakoune"]

[dependencies]
anyhow = "1.0.40"
dialoguer = "0.8.0"
lazy_static = "1.4.0"
pathdiff = "0.2.0"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.5", features = ["std"] }

[dev-dependencies]
paste = "1.0.5"
tempfile = "3.2.0"
